-- vim.api.nvim_command('colorscheme aurora')
--
vim.api.nvim_command('colorscheme terafox')
--
-- vim.g.oceanic_next_terminal_bold = 1
-- vim.g.oceanic_next_terminal_italic = 1
-- vim.api.nvim_command('colorscheme OceanicNext')
--
-- vim.api.nvim_command('colorscheme nightfox')
--
-- vim.api.nvim_command('colorscheme tender')
--
-- vim.api.nvim_command('colorscheme tokyonight')
--
-- vim.api.nvim_command('colorscheme nord')
--
-- vim.api.nvim_command('colorscheme one')
-- vim.api.nvim_command('set background=dark')
