-- vim.api.nvim_command('colorscheme aurora')
--
-- vim.api.nvim_command('colorscheme gruvbox')
--
-- vim.g.onedark_hide_endofbuffer = 1
-- vim.g.onedark_termcolors = 256
-- vim.g.onedark_terminal_italics = 1
-- vim.api.nvim_command('colorscheme onedark')
--
-- vim.g.oceanic_next_terminal_bold = 1
-- vim.g.oceanic_next_terminal_italic = 1
-- vim.api.nvim_command('colorscheme OceanicNext')
--
vim.api.nvim_command('colorscheme nightfox')
--
-- vim.api.nvim_command('colorscheme tender')
--
-- vim.api.nvim_command('colorscheme tokyonight')
--
-- vim.api.nvim_command('colorscheme nord')
